module.exports = {
    SUCCESS: 'SUCCESS',
    ERROR: 'ERROR',
    ERROR_DATABASE: 'ERROR_DATABASE',
    INVALID_PARAM: 'INVALID_PARAM',
    NOT_FOUND: 'NOT_FOUND', 
    ALREADY_CANCELED: 'ALREADY_CANCELED', // 已经被游客取消了
    ALREADY_TIMEOUT: 'ALREADY_TIMEOUT',   // 已经过期了
    ALREADY_ACCEPTED: 'ALREADY_ACCEPTED',
    ALREADY_REJECTED: 'ALREADY_REJECTED'
}